name: Build and Deploy to ACA
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Azure Docker Login
      uses: azure/docker-login@v2
      with:
          username: "sguggu"
          password: “$env:DOCKER_PASSWORD”   
          
    - name: Build and push Docker image to ACR
      run: |
        docker build . -t mycontainerregistry197.azurecr.io/django-app:latest
        docker push mycontainerregistry197.azurecr.io/django-app:latest
  
    - name: Deploy to ACA
      run: |
          az container create --resource-group Ymyrg \
                                --name containerApp555 \
                                --image mycontainerregistry197.azurecr.io/django-app:latest \
                                --cpu 1 \
                                --memory 1 \
                                --ports 80 \

