name: Build and Deploy to ACA
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
          
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: mycontainerregistry197.azurecr.io
        username: "sguggu"
        password: “$env:DOCKER_PASSWORD”

        
    - name: Build and push Docker image
      run: |
         docker build . -t mycontainerregistry197.azurecr.io/django-app:latest
         docker push mycontainerregistry197.azurecr.io/django-app:latest
    - name: Deploy to Azure Container App
      uses: azure/webapps-deploy@v2
      with:
         app-name: "mycontainerapp123"
         images: 'mycontainerregistry197.azurecr.io/django-app:latest'
