name: Build and Deploy to ACA
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
    - uses: azure/docker-login@v2
      with:
        login-server: mycontainerregistry197.azurecr.io
        username: “$env:ACR_USERNAME"
        password: “$env:ACR_PASSWORD"

    - name: Login to Azure Container Registry
    - uses: azure/docker-login@v2
      with:
          login-server: index.docker.io
          username: "sguggu"
          password: “$env:DOCKER_PASSWORD”

    - name: Pulling image
      run: |
        docker pull mycontainerregistry197.azurecr.io/django-app:latest
        docker pull django-app:latest

    - name: Build and push Docker image to ACR
      run: |
        docker build . -t mycontainerregistry197.azurecr.io/django-app:latest
        docker push mycontainerregistry197.azurecr.io/django-app:latest

    - name: Deploy to ACA
      run: |
        az container create --resource-group Ymyrg \
                              --name containerApp555 \
                              --image mycontainerregistry197.azurecr.io/django-app:latest \
                              --cpu 1 \
                              --memory 1 \
                              --ports 80 \
