name: Build and Deploy to ACA
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      
    - name: Azure Docker Login
    - uses: azure/docker-login@v2
      with:
        username: "sguggu"
        password: “$env:DOCKER_PASSWORD”


    - uses: azure/login@v2
      with:
        creds: “$env:AZURE_CREDENTIALS"
        enable-AzPSSession: true
        
    - name: Build and push Docker image to ACR
      run: |
        docker build . -t mycontainerreg555.azurecr.io/counter-image:latest
        docker push mycontainerreg555.azurecr.io/counter-image:latest
  
    - name: Deploy to ACA
      run: |
          az container create --resource-group Ymyrg \
                                --name containerApp555 \
                                --image mycontainerreg555.azurecr.io/counter-image:latest \
                                --cpu 1 \
                                --memory 1 \
                                --ports 80 \
