name: Build and Deploy to ACA
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
    - uses: azure/docker-login@v2
      with:
        login-server: contoso.azurecr.io
        username: “$env:ACR_USERNAME"
        password: “$env:ACR_PASSWORD"
    - uses: azure/docker-login@v2
      with:
          login-server: index.docker.io
          username: "sguggu"
          password: “$env:DOCKER_PASSWORD”

      run: |
        docker pull contoso.azurecr.io/private/image:latest
        docker pull private/image:latest

    - name: Build and push Docker image to ACR
      run: |
        docker build . -t mycontainerregistry197.azurecr.io/django-app:latest
        docker push mycontainerregistry197.azurecr.io/django-app:latest


    - name: deploy to acr
      runs-on: ubuntu-latest
      steps:
          - name: Login to Azure
            uses: azure/login@v1
            with:
              creds: “$env:AZURE_CREDENTIALS"

    - name: Deploy to ACA
      run: |
        az container create --resource-group Ymyrg \
                              --name containerApp555 \
                              --image mycontainerregistry197.azurecr.io/django-app:latest \
                              --cpu 1 \
                              --memory 1 \
                              --ports 80 \
